version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "minhmai"
      DB_MYSQL_PASSWORD: "minhmai"
      DB_MYSQL_NAME: "proxymanager"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'minhmai'
      MYSQL_DATABASE: 'proxymanager'
      MYSQL_USER: 'minhmai'
      MYSQL_PASSWORD: 'minhmai'
    volumes:
      - ./data/mysql:/var/lib/mysql